name: Project everfit CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: |
            mvn clean compile
        shell: cmd

      - name: Run Selenium Tests
        run: |
          mvn test
        shell: cmd

      - name: Upload Extent Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: extent-reports
          path: extentReport/HTMLReportVersion5.html